[package]
name = "cyhdev"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
incremental = false
strip = true
panic = "abort"

[profile.dev]
debug = true
panic = "abort"

[dependencies]
tokio = { version = "1.37.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] } #is the async framework that is the runtime for axum
