[package]
name = "cyhdev"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
incremental = false
strip = true
panic = "abort"

[profile.dev]
debug = true
panic = "abort"

[dependencies]
anyhow = "1.0.83"
bincode = "1.3.3"
rpassword = "7.3.1"
tokio = { version = "1.37.0", default-features = false, features = ["macros", "rt-multi-thread"] }
