//! OpenAPI documentation registration for Swagger UI.

use utoipa::OpenApi;

use crate::features::accounts::api::{
    check_if_user_exists, is_superuser, login, logout, me, reset_password,
    public_user, reset_password_request, signup, verify_user_email,
};
use crate::handlers::{
    admin::sync_i18n_cache,
    blog::{
        delete_comment, delete_post, get_posts, read_post, rescind_comment_vote, rescind_post_vote,
        search_posts, submit_comment, submit_post, update_comment, update_post, vote_comment,
        vote_post,
    },
    countries::{
        get_countries, get_country, get_language, get_languages, get_subdivisions_for_country,
    },
    geo_ip::{lookup_ip, lookup_my_ip},
    i18n::get_ui_text_bundle,
    live_chat::{cache_stats, get_messages},
    photography::{
        batch_list, batch_status, batch_upload, delete_photograph_comment, delete_photographs,
        get_photographs, read_photograph, rescind_photograph_comment_vote, rescind_photograph_vote,
        submit_photograph_comment, update_photograph_comment, upload_photograph, vote_photograph,
        vote_photograph_comment,
    },
    server::{get_host_fastfetch, healthcheck, lookup_ip_loc, root, visitor_board},
    user::upload_profile_picture,
    wasm_module::{
        delete_wasm_module, get_wasm_modules, serve_wasm, update_wasm_module,
        update_wasm_module_assets, upload_wasm_module,
    },
};

use crate::domain::{
    blog::blog::{
        Comment, CommentResponse, Post, PostInfo, PostInfoWithVote, Tag, UserBadgeInfo, VoteState,
    },
    country::{
        CountryAndSubdivisions, IsoCountry, IsoCountrySubdivision, IsoCurrency, IsoLanguage,
    },
    photography::batch::status::ProcessingStatus,
    photography::photographs::{Photograph, PhotographContext},
    photography::social::{PhotographComment, PhotographCommentResponse},
};
use crate::dto::{
    requests::{
        auth::{
            check_if_user_exists_request::CheckIfUserExistsRequest, login_request::LoginRequest,
            reset_password::ResetPasswordProcessRequest,
            reset_password_request::ResetPasswordRequest, signup_request::SignupRequest,
            verify_user_email_request::EmailValidationToken,
        },
        blog::{
            get_posts_request::GetPostsRequest, submit_comment::SubmitCommentRequest,
            submit_post_request::SubmitPostRequest, update_comment_request::UpdateCommentRequest,
            update_post_request::UpdatePostRequest, upvote_comment_request::UpvoteCommentRequest,
            upvote_post_request::UpvotePostRequest,
        },
        i18n::get_ui_text_bundle_request::GetUiTextBundleRequest,
        photography::delete_photographs_request::DeletePhotographsRequest,
        photography::submit_photograph_comment_request::SubmitPhotographCommentRequest,
        photography::update_photograph_comment_request::UpdatePhotographCommentRequest,
        photography::vote_photograph_request::VotePhotographRequest,
        wasm_module::UpdateWasmModuleRequest,
    },
    responses::{
        admin::sync_i18n_cache_response::SyncI18nCacheResponse,
        auth::{
            is_superuser_response::IsSuperuserResponse, login_response::LoginResponse,
            logout_response::LogoutResponse,
            me_response::{MeResponse, UserInfo, UserProfilePicture},
            reset_password_request_response::ResetPasswordRequestResponse,
            reset_password_response::ResetPasswordResponse, signup_response::SignupResponse,
        },
        blog::{
            delete_comment_response::DeleteCommentResponse,
            delete_post_response::DeletePostResponse, get_posts::GetPostsResponse,
            read_post_response::ReadPostResponse, submit_post_response::SubmitPostResponse,
            vote_comment_response::VoteCommentResponse, vote_post_response::VotePostResponse,
        },
        i18n::ui_text_bundle_response::UiTextBundleResponse,
        photography::batch_status_response::{
            BatchItemStatus, BatchListResponse, BatchStatusResponse, BatchUploadItem,
            BatchUploadResponse,
        },
        photography::delete_photograph_comment_response::DeletePhotographCommentResponse,
        photography::delete_photographs_response::DeletePhotographsResponse,
        photography::get_photograph_response::{
            GetPhotographsResponse, PaginationMeta, PhotographItem,
        },
        photography::read_photograph_response::ReadPhotographResponse,
        photography::vote_photograph_response::VotePhotographResponse,
        user::public_user_info_response::PublicUserInfoResponse,
        live_chat::{GetLiveChatMessagesResponse, LiveChatCacheStatsResponse, LiveChatMessageItem},
        wasm_module::{GetWasmModulesResponse, WasmModuleItem},
    },
};
use crate::errors::code_error::CodeErrorResp;
use crate::features::accounts::api::check_if_user_exists::CheckIfUserExistsResponse;
use crate::handlers::{
    blog::search_posts::SearchPostsResponse,
    countries::get_countries::GetCountriesResponse,
    server::{healthcheck::ServerHealthcheckResponse, root::RootHandlerResponse},
    wasm_module::delete_wasm_module::DeleteWasmModuleResponse,
};
use crate::openapi_envelope::FrontendResponseEnvelope;
use crate::util::geographic::ip_info_lookup::IpInfo;

/// Central OpenAPI document for Swagger UI.
#[derive(OpenApi)]
#[openapi(
    modifiers(&FrontendResponseEnvelope),
    paths(
        healthcheck::healthcheck,
        root::root_handler,
        get_host_fastfetch::get_host_fastfetch,
        visitor_board::get_visitor_board_entries,
        lookup_ip_loc::lookup_ip_location,
        lookup_ip::lookup_ip_info,
        lookup_my_ip::lookup_my_ip_info,
        get_languages::get_languages,
        get_language::get_language,
        get_countries::get_countries,
        get_country::get_country,
        get_subdivisions_for_country::get_subdivisions_for_country,
        signup::signup_handler,
        is_superuser::is_superuser_handler,
        me::me_handler,
        check_if_user_exists::check_if_user_exists_handler,
        login::login,
        reset_password_request::reset_password_request_process,
        reset_password::reset_password,
        verify_user_email::verify_user_email,
        logout::logout,
        get_posts::get_posts,
        read_post::read_post,
        submit_post::submit_post,
        vote_post::vote_post,
        vote_comment::vote_comment,
        rescind_post_vote::rescind_post_vote,
        delete_comment::delete_comment,
        update_comment::update_comment,
        delete_post::delete_post,
        update_post::update_post,
        submit_comment::submit_comment,
        rescind_comment_vote::rescind_comment_vote,
        search_posts::search_posts,
        get_ui_text_bundle::get_ui_text_bundle,
        sync_i18n_cache::sync_i18n_cache,
        get_photographs::get_photographs,
        upload_photograph::upload_photograph,
        delete_photographs::delete_photographs,
        batch_upload::batch_upload,
        batch_status::batch_status,
        batch_list::batch_list,
        read_photograph::read_photograph,
        vote_photograph::vote_photograph,
        rescind_photograph_vote::rescind_photograph_vote,
        vote_photograph_comment::vote_photograph_comment,
        rescind_photograph_comment_vote::rescind_photograph_comment_vote,
        submit_photograph_comment::submit_photograph_comment,
        update_photograph_comment::update_photograph_comment,
        delete_photograph_comment::delete_photograph_comment,
        get_messages::get_live_chat_messages,
        cache_stats::get_live_chat_cache_stats,
        public_user::get_user_info,
        upload_profile_picture::upload_profile_picture,
        get_wasm_modules::get_wasm_modules,
        upload_wasm_module::upload_wasm_module,
        update_wasm_module::update_wasm_module,
        update_wasm_module_assets::update_wasm_module_assets,
        delete_wasm_module::delete_wasm_module,
        serve_wasm::serve_wasm,
    ),
    components(
        schemas(
            CodeErrorResp,
            SignupRequest,
            SignupResponse,
            CheckIfUserExistsRequest,
            CheckIfUserExistsResponse,
            LoginRequest,
            LoginResponse,
            LogoutResponse,
            MeResponse,
            IsSuperuserResponse,
            ResetPasswordRequest,
            ResetPasswordRequestResponse,
            ResetPasswordProcessRequest,
            ResetPasswordResponse,
            EmailValidationToken,
            GetPostsRequest,
            GetPostsResponse,
            ReadPostResponse,
            SubmitPostRequest,
            SubmitPostResponse,
            UpvotePostRequest,
            VotePostResponse,
            UpvoteCommentRequest,
            VoteCommentResponse,
            SubmitCommentRequest,
            UpdateCommentRequest,
            UpdatePostRequest,
            DeleteCommentResponse,
            DeletePostResponse,
            SearchPostsResponse,
            GetUiTextBundleRequest,
            UiTextBundleResponse,
            SyncI18nCacheResponse,
            GetPhotographsResponse,
            PhotographItem,
            PaginationMeta,
            DeletePhotographsRequest,
            BatchUploadResponse,
            BatchUploadItem,
            BatchStatusResponse,
            BatchItemStatus,
            BatchListResponse,
            ProcessingStatus,
            VotePhotographRequest,
            VotePhotographResponse,
            SubmitPhotographCommentRequest,
            UpdatePhotographCommentRequest,
            DeletePhotographCommentResponse,
            DeletePhotographsResponse,
            ReadPhotographResponse,
            PhotographComment,
            PhotographCommentResponse,
            GetLiveChatMessagesResponse,
            LiveChatMessageItem,
            LiveChatCacheStatsResponse,
            UpdateWasmModuleRequest,
            GetWasmModulesResponse,
            WasmModuleItem,
            DeleteWasmModuleResponse,
            PublicUserInfoResponse,
            RootHandlerResponse,
            ServerHealthcheckResponse,
            GetCountriesResponse,
            IpInfo,
            IsoCountry,
            IsoCountrySubdivision,
            IsoCurrency,
            IsoLanguage,
            CountryAndSubdivisions,
            UserInfo,
            UserProfilePicture,
            Post,
            PostInfo,
            PostInfoWithVote,
            Comment,
            CommentResponse,
            Tag,
            UserBadgeInfo,
            VoteState,
            Photograph,
            PhotographContext,
        )
    ),
    tags(
        (name = "server", description = "Server status endpoints"),
        (name = "geo", description = "Geo / IP lookup endpoints"),
        (name = "countries", description = "Dropdown / country-language endpoints"),
        (name = "auth", description = "Authentication endpoints"),
        (name = "blog", description = "Blog endpoints"),
        (name = "i18n", description = "Internationalization endpoints"),
        (name = "admin", description = "Admin endpoints"),
        (name = "photography", description = "Photography endpoints"),
        (name = "user", description = "User endpoints"),
        (name = "live_chat", description = "Live chat HTTP endpoints"),
        (name = "wasm_module", description = "WebAssembly module endpoints")
    )
)]
pub struct ApiDoc;
