mod words;
pub use words::GUEST_NICKNAME_NOUNS;

// Curated from open English lexical datasets, then frozen into consts for
// zero-runtime I/O nickname generation:
// - WordNet 3.1 adjective satellite/common adjective lemmas.
// - WordNet 3.1 animal noun lemmas, filtered to familiar concrete animals.
pub const GUEST_NICKNAME_ADJECTIVES: &[&str] = &[
    "adventurous",
    "affable",
    "alert",
    "amber",
    "amiable",
    "breezy",
    "bright",
    "brisk",
    "bubbly",
    "calm",
    "carefree",
    "charming",
    "cheerful",
    "clever",
    "cozy",
    "crafty",
    "curious",
    "dapper",
    "dazzling",
    "eager",
    "earnest",
    "easygoing",
    "electric",
    "elegant",
    "fancy",
    "fearless",
    "festive",
    "fluffy",
    "friendly",
    "frosty",
    "gentle",
    "gleeful",
    "gossamer",
    "glimmering",
    "glossy",
    "golden",
    "graceful",
    "happy",
    "hardy",
    "hopeful",
    "helpful",
    "honeyed",
    "jovial",
    "jolly",
    "kind",
    "laughing",
    "lighthearted",
    "lively",
    "lucid",
    "lucky",
    "luminous",
    "merry",
    "mighty",
    "mellow",
    "moonlit",
    "misty",
    "modest",
    "nimble",
    "opal",
    "patient",
    "peaceful",
    "playful",
    "polite",
    "plucky",
    "proud",
    "quiet",
    "quick",
    "radiant",
    "ready",
    "rosy",
    "rugged",
    "sage",
    "sandy",
    "serene",
    "sharp",
    "shiny",
    "silky",
    "sincere",
    "skilled",
    "snappy",
    "soft",
    "sparkly",
    "spirited",
    "sprightly",
    "steady",
    "stellar",
    "swift",
    "sunny",
    "sweet",
    "tender",
    "thoughtful",
    "tidy",
    "tranquil",
    "trusty",
    "upbeat",
    "velvet",
    "vivid",
    "warm",
    "winsome",
    "wise",
    "witty",
    "zesty",
    "zippy",
    "acrobatic",
    "blithe",
    "brave",
    "buoyant",
    "canary",
    "candid",
    "crisp",
    "deft",
    "dreamy",
    "fair",
    "frisky",
    "gallant",
    "hearty",
    "jazzy",
    "keen",
    "loyal",
    "magic",
    "neat",
    "peppy",
    "perky",
    "prime",
    "silvery",
    "sleek",
    "snowy",
    "spry",
    "stout",
    "tidal",
    "twinkly",
    "verdant",
    "whimsical",
    "willowy",
    "zonal",
];

/// Two-word guest nickname chosen by a keyed seed.
///
/// Callers derive `seed` from [`super::guest_identity::GuestIdentityKey`], never
/// from the raw address, so a nickname reveals nothing about the guest's IP.
pub fn guest_nickname_from_seed(seed: u64) -> String {
    let adjective = word_from_seed(seed, GUEST_NICKNAME_ADJECTIVES, 0);
    let noun = word_from_seed(seed.rotate_left(32), GUEST_NICKNAME_NOUNS, 1);
    format!("{adjective} {noun}")
}

fn word_from_seed(seed: u64, words: &'static [&'static str], salt: usize) -> &'static str {
    if words.is_empty() {
        return "friendly";
    }
    let mixed = seed ^ ((salt as u64).wrapping_mul(0x9e3779b97f4a7c15));
    let index = (mixed as usize) % words.len();
    words[index]
}

#[cfg(test)]
mod tests;
